export type SourceTier = "Disclosed" | "Reported" | "Estimated";

export interface ArrCompany {
  slug: string;
  name: string;
  domain: string;
  /** Latest reported annualized run rate, in USD millions. */
  arrM: number;
  arrLabel: string;
  asOf: string;
  valuation?: string;
  employees?: string;
  /** Months from launch/first revenue to $100M ARR, when publicly reported. */
  monthsTo100M?: number;
  /** Growth-speed description (velocity lens) when a clean time-to-$100M is not published. */
  growthLabel?: string;
  detailHref?: string;
  sourceLabel: string;
  sourceHref: string;
  /** How the figure was obtained: company statement, press report or research estimate. */
  tier: SourceTier;
  /** Short note on the revenue definition when it differs from net ARR. */
  basisNote?: string;
}

export const ARR_COMPANIES: ArrCompany[] = [
  {
    slug: "anthropic",
    name: "Anthropic",
    domain: "anthropic.com",
    arrM: 65000,
    arrLabel: "$65B+",
    asOf: "Jul 2026",
    valuation: "$965B",
    monthsTo100M: 12,
    detailHref: "/arr-leaderboard/anthropic",
    tier: "Reported",
    sourceLabel: "Bloomberg",
    sourceHref:
      "https://www.bloomberg.com/news/articles/2026-08-17/anthropic-revenue-run-rate-surpasses-65-billion-ahead-of-ipo",
  },
  {
    slug: "openai",
    name: "OpenAI",
    domain: "openai.com",
    arrM: 25000,
    arrLabel: "~$25B",
    asOf: "Feb 2026",
    valuation: "$852B",
    monthsTo100M: 36,
    detailHref: "/arr-leaderboard/openai",
    tier: "Reported",
    sourceLabel: "CNBC / Value Add VC",
    sourceHref:
      "https://www.cnbc.com/2026/06/26/openai-anthropic-new-ai-spending-reality-as-users-shift-to-efficiency.html",
  },
  {
    slug: "databricks",
    name: "Databricks",
    domain: "databricks.com",
    arrM: 6900,
    arrLabel: "$6.9B",
    asOf: "Jun 2026",
    valuation: "$134B",
    growthLabel: "+80% YoY",
    detailHref: "/arr-leaderboard/databricks",
    tier: "Disclosed",
    sourceLabel: "CNBC / Databricks",
    sourceHref:
      "https://www.cnbc.com/2026/06/16/databricks-revenue-growth-tops-80percent-to-6point9-billion-annualized.html",
  },
  {
    slug: "cursor",
    name: "Cursor",
    domain: "cursor.com",
    arrM: 4000,
    arrLabel: "$4B+",
    asOf: "Jun 2026",
    valuation: "$60B (SpaceX acq.)",
    monthsTo100M: 12,
    detailHref: "/arr-leaderboard/cursor",
    tier: "Reported",
    sourceLabel: "New Market Pitch / TechCrunch",
    sourceHref: "https://sacra.com/research/cursor-at-100m-arr/",
  },
  {
    slug: "crusoe",
    name: "Crusoe",
    domain: "crusoe.ai",
    arrM: 2200,
    arrLabel: "~$2.2B",
    asOf: "2026",
    valuation: "~$30B (talks)",
    growthLabel: "Neocloud leader",
    detailHref: "/arr-leaderboard/crusoe",
    tier: "Reported",
    sourceLabel: "New Market Pitch",
    sourceHref: "https://newmarketpitch.com/blogs/news/ai-infrastructure-top-revenue",
    basisNote: "2026 revenue forecast presented to investors.",
  },
  {
    slug: "mercor",
    name: "Mercor",
    domain: "mercor.com",
    arrM: 2000,
    arrLabel: "~$2B",
    asOf: "Jun 2026",
    detailHref: "/arr-leaderboard/mercor",
    tier: "Reported",
    basisNote: "Gross annualized revenue, before contractor payouts.",
    sourceLabel: "The Information",
    sourceHref:
      "https://www.theinformation.com/briefings/mercor-hit-2-billion-gross-annualized-revenue",
  },
  {
    slug: "zhipu",
    name: "Zhipu AI",
    domain: "zhipuai.cn",
    arrM: 1600,
    arrLabel: "$1.6B",
    asOf: "Aug 2026",
    valuation: "~$92B mkt cap",
    growthLabel: "$67M→$1B in 7 months",
    detailHref: "/arr-leaderboard/zhipu",
    tier: "Reported",
    sourceLabel: "36Kr / earnings",
    sourceHref: "https://eu.36kr.com/en/p/3964873497320966",
  },
  {
    slug: "lambda",
    name: "Lambda",
    domain: "lambda.ai",
    arrM: 1500,
    arrLabel: "~$1.5B",
    asOf: "2026",
    growthLabel: "GPU cloud",
    detailHref: "/arr-leaderboard/lambda",
    tier: "Reported",
    sourceLabel: "New Market Pitch",
    sourceHref: "https://newmarketpitch.com/blogs/news/ai-infrastructure-top-revenue",
    basisNote: "2026 revenue expectation.",
  },
  {
    slug: "surge",
    name: "Surge AI",
    domain: "surgehq.ai",
    arrM: 1400,
    arrLabel: "$1.4B",
    asOf: "Aug 2025",
    valuation: "~$25B (talks)",
    growthLabel: "Bootstrapped",
    detailHref: "/arr-leaderboard/surge",
    tier: "Reported",
    sourceLabel: "Reuters / Sacra",
    sourceHref: "https://www.reuters.com/business/scale-ais-bigger-rival-surge-ai-seeks-up-1-billion-capital-raise-sources-say-2025-07-01/",
  },
  {
    slug: "scale",
    name: "Scale AI",
    domain: "scale.com",
    arrM: 1000,
    arrLabel: "$1B+",
    asOf: "2026",
    valuation: "$29B",
    growthLabel: "2026 guidance",
    detailHref: "/arr-leaderboard/scale",
    tier: "Reported",
    sourceLabel: "Sacra / Value Add VC",
    sourceHref: "https://sacra.com/c/scale-ai/",
    basisNote: "2025 est. ~$2B; 2026 guidance down to $1B+ after Meta stake.",
  },
  {
    slug: "fireworks",
    name: "Fireworks AI",
    domain: "fireworks.ai",
    arrM: 1000,
    arrLabel: "$1B+",
    asOf: "Jul 2026",
    valuation: "$17.5B",
    growthLabel: "5x YoY",
    detailHref: "/arr-leaderboard/fireworks",
    tier: "Disclosed",
    sourceLabel: "Fireworks / CNBC",
    sourceHref: "https://www.cnbc.com/2026/07/16/fireworks-nvidia-cloud-ai-startup-value.html",
  },
  {
    slug: "together",
    name: "Together AI",
    domain: "together.ai",
    arrM: 1000,
    arrLabel: "~$1B",
    asOf: "Jul 2026",
    valuation: "$8.3B",
    growthLabel: "Bookings $1.15B",
    detailHref: "/arr-leaderboard/together",
    tier: "Reported",
    sourceLabel: "TechCrunch / Sacra",
    sourceHref: "https://techcrunch.com/2026/07/01/neocloud-together-ai-raises-800m-leaps-to-8-3b-valuation/",
    basisNote: "Annual bookings $1.15B; revenue ~$1B by outside estimates.",
  },
  {
    slug: "moonshot",
    name: "Moonshot AI",
    domain: "moonshot.cn",
    arrM: 1000,
    arrLabel: "$1B",
    asOf: "Aug 2026",
    valuation: "~$50B",
    growthLabel: "$300M→$1B in 2 months",
    detailHref: "/arr-leaderboard/moonshot",
    tier: "Reported",
    sourceLabel: "Dealroom / 36Kr",
    sourceHref: "https://dealroom.co/news/150291-moonshot-ai-eyes-2b-annualized-revenue-as-kimi-k3-lifts-sales/",
  },
  {
    slug: "wiz",
    name: "Wiz",
    domain: "wiz.io",
    arrM: 1000,
    arrLabel: "$1B+",
    asOf: "Mar 2026, pre-close",
    monthsTo100M: 18,
    valuation: "$32B (Google acquisition)",
    detailHref: "/arr-leaderboard/wiz",
    tier: "Reported",
    sourceLabel: "Value Add VC",
    sourceHref:
      "https://valueaddvc.com/blog/how-does-wiz-make-money-cloud-security-pricing-and-the-32b-google-deal-breakdown",
  },
  {
    slug: "cognition",
    name: "Cognition",
    domain: "cognition.ai",
    arrM: 900,
    arrLabel: "~$900M",
    asOf: "Sep 2026",
    valuation: "$48B",
    growthLabel: "13x in 12 months",
    detailHref: "/arr-leaderboard/cognition",
    tier: "Disclosed",
    sourceLabel: "TechCrunch / SiliconANGLE",
    sourceHref: "https://techcrunch.com/2026/09/08/cognition-hits-48b-valuation-signaling-investors-believe-ai-coding-is-far-from-a-winner-take-all-market/",
  },
  {
    slug: "minimax",
    name: "MiniMax",
    domain: "minimaxi.com",
    arrM: 800,
    arrLabel: "$800M",
    asOf: "Aug 2026",
    valuation: "~HK$81B mkt cap",
    growthLabel: "Full-modality lab",
    detailHref: "/arr-leaderboard/minimax",
    tier: "Reported",
    sourceLabel: "36Kr / Dealroom",
    sourceHref: "https://dealroom.co/news/150291-moonshot-ai-eyes-2b-annualized-revenue-as-kimi-k3-lifts-sales/",
  },
  {
    slug: "perplexity",
    name: "Perplexity",
    domain: "perplexity.ai",
    arrM: 750,
    arrLabel: "~$750M",
    asOf: "Aug 2026",
    monthsTo100M: 22,
    detailHref: "/arr-leaderboard/perplexity",
    tier: "Estimated",
    sourceLabel: "Sacra",
    sourceHref: "https://sacra.com/c/perplexity/",
  },
  {
    slug: "fluidstack",
    name: "Fluidstack",
    domain: "fluidstack.io",
    arrM: 660,
    arrLabel: "~$660M",
    asOf: "2026",
    growthLabel: "GPU tenant-operator",
    detailHref: "/arr-leaderboard/fluidstack",
    tier: "Reported",
    sourceLabel: "New Market Pitch",
    sourceHref: "https://newmarketpitch.com/blogs/news/ai-infrastructure-top-revenue",
    basisNote: "2026 projected revenue.",
  },
  {
    slug: "elevenlabs",
    name: "ElevenLabs",
    domain: "elevenlabs.io",
    arrM: 600,
    arrLabel: "~$600M",
    asOf: "Jun 2026",
    monthsTo100M: 24,
    valuation: "$11B",
    detailHref: "/arr-leaderboard/elevenlabs",
    tier: "Estimated",
    sourceLabel: "Sacra / TechCrunch",
    sourceHref: "https://sacra.com/c/elevenlabs/",
  },
  {
    slug: "baseten",
    name: "Baseten",
    domain: "baseten.co",
    arrM: 600,
    arrLabel: "~$600M",
    asOf: "Mar 2026",
    valuation: "$13B",
    growthLabel: "~19x YoY",
    detailHref: "/arr-leaderboard/baseten",
    tier: "Reported",
    sourceLabel: "The Information / Value Add VC",
    sourceHref: "https://valueaddvc.com/blog/baseten-valuation-revenue-2026-13b-ai-inference",
  },
  {
    slug: "replit",
    name: "Replit",
    domain: "replit.com",
    arrM: 525,
    arrLabel: "~$525M",
    asOf: "Apr 2026",
    monthsTo100M: 14,
    valuation: "$9B",
    detailHref: "/arr-leaderboard/replit",
    tier: "Estimated",
    sourceLabel: "Sacra",
    sourceHref: "https://sacra.com/research/replit-passes-500m-year/",
  },
  {
    slug: "lovable",
    name: "Lovable",
    domain: "lovable.dev",
    arrM: 500,
    arrLabel: "$500M+",
    asOf: "Jun 2026",
    monthsTo100M: 8,
    valuation: "$6.6B",
    employees: "~146",
    detailHref: "/arr-leaderboard/lovable",
    tier: "Disclosed",
    sourceLabel: "TechCrunch",
    sourceHref:
      "https://techcrunch.com/2026/06/09/lovable-says-it-has-hit-500m-in-annualized-revenue-with-1-million-new-projects-a-week/",
  },
  {
    slug: "xai",
    name: "xAI",
    domain: "x.ai",
    arrM: 500,
    arrLabel: "~$500M",
    asOf: "mid-2026",
    valuation: "$230B (pre-merger)",
    growthLabel: "Targeting $2B in 2026",
    detailHref: "/arr-leaderboard/xai",
    tier: "Reported",
    sourceLabel: "Bloomberg via Sacra",
    sourceHref: "https://valueaddvc.com/blog/xai-revenue-how-grok-and-the-api-actually-make-money",
    basisNote: "Standalone AI ARR; excludes X advertising revenue.",
  },
  {
    slug: "cohere",
    name: "Cohere",
    domain: "cohere.com",
    arrM: 500,
    arrLabel: "~$500M",
    asOf: "2026",
    valuation: "$6.5B",
    growthLabel: "Enterprise API",
    detailHref: "/arr-leaderboard/cohere",
    tier: "Reported",
    sourceLabel: "Presenc AI",
    sourceHref: "https://presenc.ai/research/ai-lab-revenue-and-valuation-2026",
  },
  {
    slug: "deepseek",
    name: "DeepSeek",
    domain: "deepseek.com",
    arrM: 500,
    arrLabel: "~$500M",
    asOf: "2026",
    valuation: "~$50B",
    growthLabel: "10x revenue in 7 months",
    detailHref: "/arr-leaderboard/deepseek",
    tier: "Reported",
    sourceLabel: "The Information / AI Weekly",
    sourceHref: "https://aiweekly.co/alerts/deepseek-nears-500m-annualized-revenue-plans-2027-ipo",
  },
  {
    slug: "midjourney",
    name: "Midjourney",
    domain: "midjourney.com",
    arrM: 500,
    arrLabel: "~$500M",
    asOf: "2026",
    growthLabel: "Bootstrapped, profitable",
    detailHref: "/arr-leaderboard/midjourney",
    tier: "Estimated",
    sourceLabel: "Sacra / GetLatka",
    sourceHref: "https://valueaddvc.com/blog/how-does-midjourney-make-money-500m-arr-zero-funding-and-the-ai-image-business-model-explained",
    basisNote: "Company never disclosed revenue; third-party estimates.",
  },
  {
    slug: "vast",
    name: "VAST Data",
    domain: "vastdata.com",
    arrM: 500,
    arrLabel: "$500M+",
    asOf: "2026",
    growthLabel: "Committed ARR",
    detailHref: "/arr-leaderboard/vast",
    tier: "Reported",
    sourceLabel: "New Market Pitch",
    sourceHref: "https://newmarketpitch.com/blogs/news/ai-infrastructure-top-revenue",
    basisNote: "Committed annual recurring revenue.",
  },
  {
    slug: "mistral",
    name: "Mistral",
    domain: "mistral.ai",
    arrM: 400,
    arrLabel: "$400M",
    asOf: "Jan 2026",
    valuation: "$13.8B",
    growthLabel: "20x YoY",
    detailHref: "/arr-leaderboard/mistral",
    tier: "Reported",
    sourceLabel: "Sacra / FT",
    sourceHref: "https://sacra.com/research/400m-year-napoleon-of-sovereign-ai/",
  },
  {
    slug: "fal",
    name: "fal.ai",
    domain: "fal.ai",
    arrM: 400,
    arrLabel: "~$400M",
    asOf: "2026",
    growthLabel: "Inference platform",
    detailHref: "/arr-leaderboard/fal",
    tier: "Estimated",
    sourceLabel: "Sacra",
    sourceHref: "https://newmarketpitch.com/blogs/news/ai-infrastructure-top-revenue",
  },
  {
    slug: "harvey",
    name: "Harvey",
    domain: "harvey.ai",
    arrM: 350,
    arrLabel: "~$350M",
    asOf: "Jul 2026",
    monthsTo100M: 36,
    detailHref: "/arr-leaderboard/harvey",
    tier: "Reported",
    sourceLabel: "Sacra / The Information",
    sourceHref: "https://sacra.com/c/harvey/",
  },
  {
    slug: "ai21",
    name: "AI21 Labs",
    domain: "ai21.com",
    arrM: 350,
    arrLabel: "~$350M",
    asOf: "2026",
    valuation: "$1.5B",
    growthLabel: "Enterprise LLMs",
    detailHref: "/arr-leaderboard/ai21",
    tier: "Estimated",
    sourceLabel: "Presenc AI",
    sourceHref: "https://presenc.ai/research/ai-lab-revenue-and-valuation-2026",
  },
  {
    slug: "suno",
    name: "Suno",
    domain: "suno.com",
    arrM: 300,
    arrLabel: "$300M",
    asOf: "Feb 2026",
    valuation: "$5.4B",
    growthLabel: "$200M→$300M in 3 months",
    detailHref: "/arr-leaderboard/suno",
    tier: "Disclosed",
    sourceLabel: "TechCrunch / Sacra",
    sourceHref: "https://techcrunch.com/2026/02/27/ai-music-generator-suno-hits-2-million-paid-subscribers-and-300m-in-annual-recurring-revenue/",
  },
  {
    slug: "modal",
    name: "Modal",
    domain: "modal.com",
    arrM: 300,
    arrLabel: "~$300M",
    asOf: "2026",
    growthLabel: "Serverless compute",
    detailHref: "/arr-leaderboard/modal",
    tier: "Reported",
    sourceLabel: "New Market Pitch",
    sourceHref: "https://newmarketpitch.com/blogs/news/ai-infrastructure-top-revenue",
  },
  {
    slug: "glean",
    name: "Glean",
    domain: "glean.com",
    arrM: 300,
    arrLabel: "$300M+",
    asOf: "May 2026",
    detailHref: "/arr-leaderboard/glean",
    tier: "Disclosed",
    sourceLabel: "Glean / TechCrunch",
    sourceHref:
      "https://www.glean.com/press/glean-surpasses-300m-arr-unrivaled-enterprise-context-fuels-ai-adoption",
  },
  {
    slug: "runway",
    name: "Runway",
    domain: "runwayml.com",
    arrM: 200,
    arrLabel: "$200M",
    asOf: "Sep 2026",
    valuation: "$5.3B",
    growthLabel: "$100M→$200M in 5 months",
    detailHref: "/arr-leaderboard/runway",
    tier: "Disclosed",
    sourceLabel: "Bloomberg / PYMNTS",
    sourceHref: "https://www.pymnts.com/news/artificial-intelligence/2026/runway-ai-hits-200-million-revenue-and-expands-robotics-capabilities/",
  },
  {
    slug: "heygen",
    name: "HeyGen",
    domain: "heygen.com",
    arrM: 200,
    arrLabel: "$200M",
    asOf: "Jun 2026",
    growthLabel: "Doubled in 8 months",
    detailHref: "/arr-leaderboard/heygen",
    tier: "Disclosed",
    sourceLabel: "HeyGen / Upstarts",
    sourceHref: "https://www.upstartsmedia.com/p/exclusive-heygen-200m-arr-without-burn",
  },
  {
    slug: "sierra",
    name: "Sierra",
    domain: "sierra.ai",
    arrM: 200,
    arrLabel: "$200M",
    asOf: "May 2026",
    monthsTo100M: 21,
    valuation: "$15.8B",
    detailHref: "/arr-leaderboard/sierra",
    tier: "Reported",
    sourceLabel: "Sacra / CNBC",
    sourceHref: "https://sacra.com/c/sierra/",
  },
  {
    slug: "synthesia",
    name: "Synthesia",
    domain: "synthesia.io",
    arrM: 150,
    arrLabel: "~$150M",
    asOf: "2026",
    valuation: "$4B",
    detailHref: "/arr-leaderboard/synthesia",
    tier: "Estimated",
    sourceLabel: "Sacra / CNBC",
    sourceHref: "https://sacra.com/c/synthesia/",
  },
  {
    slug: "clay",
    name: "Clay",
    domain: "clay.com",
    arrM: 150,
    arrLabel: "$150M",
    asOf: "May 2026",
    valuation: "$7.1B",
    detailHref: "/arr-leaderboard/clay",
    tier: "Estimated",
    sourceLabel: "Sacra / Clay",
    sourceHref: "https://sacra.com/research/clay-crosses-150m-year/",
  },
  {
    slug: "emergent",
    name: "Emergent",
    domain: "emergent.ai",
    arrM: 120,
    arrLabel: "~$120M",
    asOf: "Jul 2026",
    growthLabel: "+70% in 4 months",
    detailHref: "/arr-leaderboard/emergent",
    tier: "Reported",
    sourceLabel: "TechCrunch",
    sourceHref: "https://newmarketpitch.com/blogs/news/ai-code-assistant-top-revenue",
  },
  {
    slug: "gamma",
    name: "Gamma",
    domain: "gamma.app",
    arrM: 100,
    arrLabel: "$100M",
    asOf: "2026",
    valuation: "$2.1B",
    growthLabel: "50 employees",
    detailHref: "/arr-leaderboard/gamma",
    tier: "Reported",
    sourceLabel: "AI 50 / YouTube",
    sourceHref: "https://www.youtube.com/watch?v=mKEr3NKBYSk",
  },
  {
    slug: "decagon",
    name: "Decagon",
    domain: "decagon.ai",
    arrM: 100,
    arrLabel: "$100M",
    asOf: "Jul 2026",
    valuation: "$4.5B",
    growthLabel: "3x YoY",
    detailHref: "/arr-leaderboard/decagon",
    tier: "Reported",
    sourceLabel: "Sacra / Newcomer",
    sourceHref: "https://valueaddvc.com/pulse/decagon-100m-arr-ai-customer-agents-2026",
  },
  {
    slug: "abridge",
    name: "Abridge",
    domain: "abridge.com",
    arrM: 100,
    arrLabel: "$100M+",
    asOf: "mid-2025",
    valuation: "$5.3B",
    growthLabel: "$6M→$100M in 18 months",
    detailHref: "/arr-leaderboard/abridge",
    tier: "Reported",
    sourceLabel: "Sacra / Value Add VC",
    sourceHref: "https://valueaddvc.com/blog/abridge-valuation-2026-5-3b-100m-arr-and-how-the-ai-scribe-beat-nuance-and-ambience",
  },
  {
    slug: "evenup",
    name: "EvenUp",
    domain: "evenup.ai",
    arrM: 100,
    arrLabel: "$100M",
    asOf: "Jul 2026",
    valuation: "$2B",
    growthLabel: "5x in 2 years",
    detailHref: "/arr-leaderboard/evenup",
    tier: "Reported",
    sourceLabel: "ARR Club / Sacra",
    sourceHref: "https://www.arr.club/evenup",
  },
  {
    slug: "skild",
    name: "Skild AI",
    domain: "skild.ai",
    arrM: 100,
    arrLabel: "$100M",
    asOf: "Sep 2026",
    valuation: "$14B",
    monthsTo100M: 10,
    detailHref: "/arr-leaderboard/skild",
    tier: "Reported",
    sourceLabel: "Bloomberg",
    sourceHref: "https://www.bloomberg.com/news/articles/2026-09-10/robotics-startup-skild-ai-hits-100-million-in-revenue-run-rate",
  },
  {
    slug: "stability",
    name: "Stability AI",
    domain: "stability.ai",
    arrM: 90,
    arrLabel: "~$90M",
    asOf: "2026",
    valuation: "$300M (down round)",
    growthLabel: "Open image models",
    detailHref: "/arr-leaderboard/stability",
    tier: "Estimated",
    sourceLabel: "Presenc AI",
    sourceHref: "https://presenc.ai/research/ai-lab-revenue-and-valuation-2026",
  },
  {
    slug: "coderabbit",
    name: "CodeRabbit",
    domain: "coderabbit.ai",
    arrM: 50,
    arrLabel: "~$50M",
    asOf: "2026",
    growthLabel: "AI code review",
    detailHref: "/arr-leaderboard/coderabbit",
    tier: "Estimated",
    sourceLabel: "New Market Pitch",
    sourceHref: "https://newmarketpitch.com/blogs/news/ai-code-assistant-top-revenue",
  },
  {
    slug: "hippocratic",
    name: "Hippocratic AI",
    domain: "hippocraticai.com",
    arrM: 50,
    arrLabel: "~$50M+",
    asOf: "2026",
    valuation: "$1.64B",
    growthLabel: "Patient-facing agents",
    detailHref: "/arr-leaderboard/hippocratic",
    tier: "Estimated",
    sourceLabel: "Presenc AI",
    sourceHref: "https://presenc.ai/research/medical-ai-tools-landscape-2026",
    basisNote: "ARR not precisely disclosed; estimate at $50M threshold.",
  },
  {
    slug: "luma",
    name: "Luma AI",
    domain: "lumalabs.ai",
    arrM: 80,
    arrLabel: "~$80M",
    asOf: "2026",
    valuation: "$4B",
    growthLabel: "Dream Machine",
    detailHref: "/arr-leaderboard/luma",
    tier: "Estimated",
    sourceLabel: "Sacra / a16z",
    sourceHref: "https://morphed.app/stats/ai-video-generation-statistics",
    basisNote: "ARR not precisely disclosed; estimate.",
  },
  {
    slug: "deepgram",
    name: "Deepgram",
    domain: "deepgram.com",
    arrM: 50,
    arrLabel: "~$50M+",
    asOf: "2026",
    valuation: "$1.3B",
    growthLabel: "Voice infrastructure",
    detailHref: "/arr-leaderboard/deepgram",
    tier: "Estimated",
    sourceLabel: "Value Add VC",
    sourceHref: "https://valueaddvc.com/blog/how-does-elevenlabs-make-money-api-enterprise-voice-agents-and-the-business-model-breakdown",
    basisNote: "ARR not precisely disclosed; estimate at $50M threshold.",
  },
];
