import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import matter from "gray-matter";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const BLOG_DIR = path.join(ROOT, "content", "blog");
const OUT_DIR = path.join(ROOT, "src", "data");
const OUT_FILE = path.join(OUT_DIR, "blog-data.ts");

interface BlogPost {
  slug: string;
  title: string;
  description: string;
  date: string;
  updated?: string;
  category: string;
  keywords: string[];
  author: string;
  image?: string;
  readingMinutes: number;
  related: string[];
}

/** Convert a Date or string to YYYY-MM-DD format */
function toDateString(value: unknown): string {
  if (value instanceof Date) {
    return value.toISOString().slice(0, 10);
  }
  if (typeof value === "string") {
    // If already YYYY-MM-DD, return as-is
    if (/^\d{4}-\d{2}-\d{2}$/.test(value)) return value;
    const d = new Date(value);
    if (!isNaN(d.getTime())) return d.toISOString().slice(0, 10);
  }
  return "";
}

function main() {
  if (!fs.existsSync(BLOG_DIR)) {
    console.log("No blog content directory found. Skipping blog data generation.");
    generateEmpty();
    return;
  }

  const files = fs.readdirSync(BLOG_DIR).filter((f) => f.endsWith(".md"));

  if (files.length === 0) {
    console.log("No blog posts found. Generating empty blog data.");
    generateEmpty();
    return;
  }

  const posts: BlogPost[] = [];
  const contentMap: Record<string, string> = {};

  for (const file of files) {
    const fullPath = path.join(BLOG_DIR, file);
    const raw = fs.readFileSync(fullPath, "utf-8");
    const { data, content } = matter(raw);

    const post: BlogPost = {
      slug: data.slug || "",
      title: data.title || "",
      description: data.description || "",
      date: toDateString(data.date),
      category: data.category || "",
      keywords: Array.isArray(data.keywords) ? data.keywords : [],
      author: data.author || "",
      readingMinutes: Number(data.readingMinutes) || 0,
      related: Array.isArray(data.related) ? data.related : [],
    };

    if (data.updated) post.updated = toDateString(data.updated);
    if (data.image) post.image = String(data.image);

    posts.push(post);
    contentMap[post.slug] = content.trim();
  }

  // Sort by date descending
  posts.sort(
    (a, b) => new Date(b.date).getTime() - new Date(a.date).getTime()
  );

  generateOutput(posts, contentMap);
  console.log(`Generated blog data with ${posts.length} post(s).`);
}

function generateEmpty() {
  generateOutput([], {});
}

function generateOutput(posts: BlogPost[], contentMap: Record<string, string>) {
  if (!fs.existsSync(OUT_DIR)) {
    fs.mkdirSync(OUT_DIR, { recursive: true });
  }

  const postsJson = JSON.stringify(posts, null, 2);
  const contentJson = JSON.stringify(contentMap, null, 2);

  const output = `// Auto-generated by scripts/build-blog-data.ts. Do not edit manually.
import type { BlogPost } from "@/lib/blog";

export const BLOG_POSTS: BlogPost[] = ${postsJson};

export const BLOG_CONTENT: Record<string, string> = ${contentJson};
`;

  fs.writeFileSync(OUT_FILE, output, "utf-8");
}

main();
